version: "2"
networks:
    ech-network:
        driver: bridge
services:
    ech-frontend:
        image: ech-frontend:latest
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./ech-frontend:/ech-frontend
            - /ech-frontend/node_modules
            - /ech-frontend/code-hub-frontend
        links:
            - ech-backend
        depends_on:
            - ech-backend
        networks:
            - ech-network
    ech-backend:
        image: ech-backend:latest
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - ./ech-backend:/ech-backend
            - /ech-backend/node_modules
        depends_on:
            - mongodb
        networks:
            - ech-network
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth
        networks:
            - ech-network